package com.richardbrenkus.hospitalshiftscheduler.config.constants;

public enum ActivityType {
    USER_LOGIN_SUCCEEDED,
    USER_LOGIN_FAILED,
    USER_LOGOUT,
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    PASSWORD_CHANGED,
    SHIFT_REQUEST_CREATED,
    SHIFT_REQUEST_UPDATED,
    SHIFT_REQUEST_DELETED,
    ALL_SHIFT_REQUESTS_DELETED,
    SCHEDULE_CALCULATION_STARTED,
    SCHEDULE_CALCULATION_COMPLETED,
    SCHEDULE_CALCULATION_FAILED,
    SCHEDULE_STORED,
    ADMIN_SETTINGS_CHANGED,
    PLANNED_CLEANUP_EXECUTED,
    PLANNED_CLEANUP_FAILED,
    REMINDER_EMAIL_SENT,
    REMINDER_EMAIL_FAILED,
    REMINDER_EMAIL_JOB_CREATED,
    REMINDER_EMAIL_JOB_CREATION_FAILED,
    REMINDER_EMAILS_SENT,
    REMINDER_EMAIL_JOBS_CANCELED
}
